spring:
  application:
    name: map-locator
  datasource:
    driver:
      class-name: org.postgresql.Driver
    url: ${app.datasource.url}
    username: admin
    password: admin
    name: adminDS
    hikari:
      auto-commit: true
      transaction:
        isolation: TRANSACTION_READ_COMMITTED
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
  liquibase:
    enabled: false
  profiles:
    include:
      - tomtomApi

  ai:
    local:
      url: http://localhost:12434/engines/llama.cpp/v1/chat/completions
      model: ai/llama3.2:3B-Q4_0

app:
  datasource:
    url:
      jdbc:postgresql://127.0.0.1:5432/map_locator


  mok:
    security:
      authToken:
        timeout-in-minutes: 15
        key: your-very-secret-key
      cors:
        allowedOrigins:
          - http://localhost:5173
