name: Tests

on:
  push:
    branches: [ "**" ]

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      TOMTOM_API_KEY: ${{ secrets.TOMTOM_API_KEY }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
      - name: Run test with Maven
        run: |
          mvn clean install -DskipTests \
          -Dapp.mok.security.authToken.key="${JWT_SECRET}" \
          -Dtomtom.api.key="${TOMTOM_API_KEY}" \